### ISSUE TITLE
Bot gets stuck on "Game start"

### ISSUE THREAD

**Issue by jason00-r** [linus-jansson/btd6farmer#12]
I start the bot and it selects the hero, map, and difficulty. Then it starts the game. but after the bot closes the popup mentioning impoppable, it just sits watching the map and not doing anything. The last thing printed in the command line is "Game start". Playing on fullscreen resolution 2560x1440.

Below is a screenshot of the output after I kill the python code from the command line.
![image](https://user-images.githubusercontent.com/16599377/175506433-7282a4c5-eb4a-493b-8bfa-08b0e4f8db1b.png)

**Comment by linus-jansson** [comment]
Seems to be fixed with #13 after testing

**Comment by jason00-r** [comment]
> Seems to be fixed with #13 after testing

The bot will now start the round, but it does not place any monkey towers down. It looks like it might be trying to place Obyn, but I'm not 100% sure.
