### ISSUE TITLE
Bot starts game, but does not place any towers to pop balloons

### ISSUE THREAD

**Issue by jason00-r** [linus-jansson/btd6farmer#15]
The bot won't place any monkey towers. It just starts the first round. After issue #12 was fixed, this is the new behavior.

**Comment by jason00-r** [comment]
bot will do nothing and the game will end due to 0 hearts left

**Comment by linus-jansson** [comment]
What OS are you running on?

**Comment by jason00-r** [comment]
In the game, my screen size is set to 2560x1440 in the settings. I tried in both full screen and windowed mode. Both just start and do not place any towers.

**Comment by linus-jansson** [comment]
Could you try with the latest release and see if anything happens now?

**Comment by jason00-r** [comment]
> Could you try with the latest release and see if anything happens now?

That did not fix the issue. 

I did notice that the cursor moved to the left of the map quickly and I circled the area roughly with a white circle in the screenshot below.

![image](https://user-images.githubusercontent.com/16599377/176779295-70da3ac6-2870-4342-8cba-76c74ea50eab.png)

**Comment by jason00-r** [comment]
In that screenshot I have the cursor set to X-Large, but I also have tried with the normal size. It did not help.

**Comment by linus-jansson** [comment]
Could you check what python version you have with `py --version` in your CMD or terminal? Also do a `pip freeze` and send the output here

**Comment by jason00-r** [comment]
> Could you check what python version you have with `py --version` in your CMD or terminal? Also do a `pip freeze` and send the output here

C:\Users\Jason>py --version
Python 3.10.5


C:\Users\Jason>pip freeze
Fatal error in launcher: Unable to create process using '"c:\program files\python39\python.exe"  "C:\Program Files\Python39\Scripts\pip.exe" freeze': The system cannot find the file specified.


C:\Users\Jason>python -m pip freeze
keyboard==0.13.5
mouse==0.7.1
MouseInfo==0.1.3
numpy==1.22.3
opencv-python==4.5.5.64
packaging==21.3
Pillow==9.1.1
PyAutoGUI==0.9.53
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pyparsing==3.0.9
pyperclip==1.8.2
PyRect==0.2.0
PyScreeze==0.1.28
pytesseract==0.3.9
pytweening==1.0.4

**Comment by pozm** [comment]
i also encounter this issue, the game starts and it places no towers. i can provide the same statistics

**Comment by pozm** [comment]
After debugging i have figured out that it is due to the ocr being wildly inaccurate spewing out inconstant results 
![image](https://user-images.githubusercontent.com/44528100/178524234-4d45262d-3d99-40a6-b3d4-cf02a204e60c.png)
(don't even try with autohdr as there is no hope)

**Comment by linus-jansson** [comment]
Woah thats way off..

Could always try with implementing tesserocr instead of pytesseract, but I think it will just improve the performance and not the accuracy. I also found [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) which can be tested, maybe that will fix the issue!

> After debugging i have figured out that it is due to the ocr being wildly inaccurate spewing out inconstant results

Would it be possible if you could try to view the image that its capturing on your instance by adding:
```py
cv2.imshow('Screenshot', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
```
in https://github.com/linus-jansson/btd6farmer/blob/5803d6e1c55a5912543844e358143d51de869e21/bot.py#L67-L71
on line 70 to see if it is even capturing the right place of the screen?

**Comment by pozm** [comment]
I've already looked at the images it's produced and they don't look particularly wrong but I'll upload the images for the stages when I'm back on my computer.

**Comment by pozm** [comment]
this is what tensorflow sees:
![pog2](https://user-images.githubusercontent.com/44528100/179059901-90dfe0d3-90a8-428a-abf4-f73e89143aac.png)

this is the image which is captured before post processing / converting to black and white:
![temp](https://user-images.githubusercontent.com/44528100/179060040-bee17076-753f-4e1a-9119-39468db6300f.png)

hope these images help improve the software
[my resolution is 5120x1440 so that's why there is excess black pixels but that should be happening i think due to padding mechanism]

**Comment by jason00-r** [comment]
Something appears to be wrong still. 

I got a defeat at round 35 from camo balloons. Dart monkeys were not being upgraded at all. 

Then after restarting the script, I got a defeat at round 63 with $38,964. 
dart monkey1 0-0-2
dart monkey2 0-0-0
super monkey 0-0-1
both sub 2-0-3
alchemist 3-0-0
obyn placed and level 13
both monkey villages 0-0-2

**Comment by linus-jansson** [comment]
> Something appears to be wrong still.
> 
> I got a defeat at round 35 from camo balloons. Dart monkeys were not being upgraded at all.
> 
> Then after restarting the script, I got a defeat at round 63 with $38,964. dart monkey1 0-0-2 dart monkey2 0-0-0 super monkey 0-0-1 both sub 2-0-3 alchemist 3-0-0 obyn placed and level 13 both monkey villages 0-0-2

I will open that in a new issue to seperate the subjects a bit

**Comment by jason00-r** [comment]
> > Something appears to be wrong still.
> > I got a defeat at round 35 from camo balloons. Dart monkeys were not being upgraded at all.
> > Then after restarting the script, I got a defeat at round 63 with $38,964. dart monkey1 0-0-2 dart monkey2 0-0-0 super monkey 0-0-1 both sub 2-0-3 alchemist 3-0-0 obyn placed and level 13 both monkey villages 0-0-2
> 
> I will open that in a new issue to seperate the subjects a bit

That makes sense. I will close this issue then. My original issue of no towers being placed is solved.
