### ISSUE TITLE
Gameplan not really working as aspected

### ISSUE THREAD

**Issue by linus-jansson** [linus-jansson/btd6farmer#16]
>I got a defeat at round 35 from camo balloons. Dart monkeys were not being upgraded at all.
>
>Then after restarting the script, I got a defeat at round 63 with $38,964.
>dart monkey1 0-0-2
>dart monkey2 0-0-0
>super monkey 0-0-1
>both sub 2-0-3
>alchemist 3-0-0
>obyn placed and level 13
>both monkey villages 0-0-2

Reference from #15 [..](https://github.com/linus-jansson/btd6farmer/issues/15#issuecomment-1185026244)

**Comment by jason00-r** [comment]
I watched it run for a full game and then went out and came back an hour or two later. Still running fine. 

This issue seems to be fixed for me with your recent update #17  @linus-jansson 

```
python main.py "\\Instructions\\Dark_Castle_Hard_Standard"
Setting up Bot...
Setup Complete.
Waiting for 5 seconds... Please select the Bloons TD 6 window during this time.
Selecting obyn if not selected
selecting map
Game start
Starting first round
level up detected
selecting map
Game start
Starting first round
selecting map
Game start
Starting first round
selecting map
Game start
Starting first round
selecting map
Game start
Starting first round
level up detected
selecting map
Game start
Starting first round
selecting map
Game start
Starting first round
selecting map
Game start
Starting first round
```
