### ISSUE TITLE
Possibility to choose gamemode for map

### ISSUE THREAD

**Issue by 3lectr0o** [linus-jansson/btd6farmer#18]
bot just does nothing when winning or losing the game

**Comment by 3lectr0o** [comment]
it also does not get rid of the pop up of the new gained monkey knowledge which stops the game

**Comment by linus-jansson** [comment]
What screen resolution are you on?
Are you on the main branch?
Is there any error code or is it just idling?

**Comment by 3lectr0o** [comment]
> What screen resolution are you on? Are you on the main branch? Is there any error code or is the bot just idling? Also what commit are you on? You can check that using `git show` in your cmd when in the btd6farmer folder if you have git installed.
> 
> EDIT: also please test with the latest commit on the main branch as there are some changes to the bot.

I'm on 1080p and the main branch. On the latest commit: "da9a8393cf8683a536544b1b0f7d1d97148aefae"

bot is just idling after a win, lose or a pop up, could this be a problem with tesseract?

**Comment by 3lectr0o** [comment]
nvm I'm a freakin idiot xD game was on my native language and tesseract couldn't recognize it
but anyway, could you add a function to press the Ok Button after starting impoppable? or will this be included with a new gameplan? I can't make it work tho :D

anyways good work

**Comment by linus-jansson** [comment]
Could be a possibility that something like that will be added. Also mentioned in #19 

 It should work with the current gameplan however, what I have experienced is that something differs between standard mode and chimps as on chimps when testing no ballons get thorugh but when testing on standard I lose around 11 hearts early in the game. So I think that be a big deal on impoppable and something i'll have to look into before making it possible to choose.

I guess there is some difference on the bloon spawn rate or that some thing change in the game plan file during a commit.

**Comment by linus-jansson** [comment]
Im working on a guide to create own gameplans in PR #25, this will add the capability to play the current gameplan on chimps and impoppable
