### ISSUE TITLE
I select CHIMPS mode and cant start

### ISSUE THREAD

**Issue by Capoouo** [linus-jansson/btd6farmer#19]
![image](https://user-images.githubusercontent.com/100028637/179748216-01a48c7a-560a-46d4-9597-d371236b1176.png)
He can't press OK

**Comment by ian890608ian** [comment]
then always just press start

**Comment by linus-jansson** [comment]
No problem, you used to be, but it seems to be more benificial to use it on standard as to the money/time is greater..

Could be possibility in the future to use chimps also as the gameplan has the instructions needed for it

**Comment by ian890608ian** [comment]
> No problem, you used to be, but it seems to be more benificial to use it on standard as to the money/time is greater..
> 
> Could be possibility in the future to use chimps also as the gameplan has the instructions needed for it

OK thanks~
