### ISSUE TITLE
bot not closing Monkey Knowledge popup

### ISSUE THREAD

**Issue by 3lectr0o** [linus-jansson/btd6farmer#29]
It all worked fine few days ago
bot can't close the Monkey knowledge popup

I'm on the main branch
commit 91cbe830ea6f7e9627f21fe70f45a5550e322aad on 1080p

**Comment by linus-jansson** [comment]
![1440_monkey_knowledge](https://user-images.githubusercontent.com/30862662/180652214-890faec1-ede8-4af2-a476-b848029a7f40.png)
It's this monkey knowledge right? The book.. That image does not exist for 1080p but im working on it on #25

**Comment by 3lectr0o** [comment]
doesn't work

**Comment by 3lectr0o** [comment]
`self.click(middle_of_screen, amount=3)`
3 instead of 2 works for now

**Comment by linus-jansson** [comment]
My bad, I mixed up the main branch and the dev branch! I'm working on this and it will be pushed to main as soon as it's done! Will leave it open until the PR is closed if anyone else experience this issue! But yeah changing `amount=2` to `amount=3` should work!
https://github.com/linus-jansson/btd6farmer/blob/91cbe830ea6f7e9627f21fe70f45a5550e322aad/Bot.py#L54-L58

**Comment by linus-jansson** [comment]
Should be fixed in latest PR
