### ISSUE TITLE
Dynamic abilityAvaliabe

### ISSUE THREAD

**Issue by LegendRed01** [linus-jansson/btd6farmer#34]
I was planing to help out with the 
`TODO: Make this more general to support more gameplans`

so i was wondering where did you get the time used in 
`abilityAvaliabe(ability_one_timer, 35)` from and if those ability times are static for each hero.

**Comment by linus-jansson** [comment]
My first guess that I was actually counting how long there was a cooldown however, did I quick search on the BTD 6 fandom page found the timers for [obyn](https://bloons.fandom.com/wiki/Obyn_Greenfoot_(BTD6)#Upgrades). My best guess is that the other heros also have the same page! Cheers in advance!
