### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Somethingcom515** [linus-jansson/btd6farmer#75]
import mouse, keyboard
ModuleNotFoundError: No module named 'mouse'

**Comment by Somethingcom515** [comment]
import mss
ModuleNotFoundError: No module named 'mss'

**Comment by linus-jansson** [comment]
Seems like you have not installed the dependencies, please follow the [installation guide](https://github.com/linus-jansson/btd6farmer#installation-of-dependencies) in the README

**Comment by youmustp** [comment]
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by youmustp** [comment]
how do i fix type erorrer
