### ISSUE TITLE
Could you add a bot for impoppable

### ISSUE THREAD

**Issue by Tiebe** [linus-jansson/btd6farmer#9]
I'm really struggling to beat dark castle impoppable, could you add a bot for it?

**Comment by Shaksos** [comment]
the bot here is able to do it if you manually edit the coordinates, I did some maths for mine and made some more entries myself. You should also edit instructions to place the first towers a bit before round 6, unless you feel like handling it manually to round 6

**Comment by Tiebe** [comment]
When I try to run it it starts, places 1 dart monkey and 1 monkey sub and then presses escape, do you know why this is? Or would you be able to share your code?

**Comment by Shaksos** [comment]
> 

the only thing i really changed was where the bot would select the game mode. in Static.py there's a list of button positions. By default, the bot uses the CHIMP_MODE. you can choose here, if you want to edit this entry, or make a new entry and change bot.py to use the new entry instead. for the values, i used the info from the other button positions and calculated the position in pixels. Hope this helps

**Comment by linus-jansson** [comment]
> And @Shaksos impoppable also starts at round 6 right?

Impoppable & Chimps start both on round 6. You should basically just need to do as Shaksos says by changing the CHIMPS_MODE cordinates in `static.py` as CHIMPS are more restricted (Monkey knowledge etc).

In the repo there is a `pos.py` which you can run to see the cordinates of the button if you feel like changing it.

> When I try to run it it starts, places 1 dart monkey and 1 monkey sub and then presses escape, do you know why this is? Or would you be able to share your code?

Are you still experiencing this?

**Comment by Tiebe** [comment]
> Are you still experiencing this?

Yep, after it sets the first dart monkey to target strong it pauses the game.
